spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.yandex.ru
    port: 587
    username: peredereev-in@yandex.ru
    password: znagrkldpfnhgvlw
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.yandex.ru
          starttls:
            enable: true

jwt:
  access-token-expiration: 900000   # 15 минут
  refresh-token-expiration: 604800000 # 7 дней (пока не используется, но готово)
  rsa:
    private-key-path: ${JWT_PRIVATE_KEY_PATH:keys/private.pem}
    public-key-path: ${JWT_PUBLIC_KEY_PATH:keys/public.pem}


server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework.security: DEBUG
    com.sun.mail.smtp: DEBUG

kind: Application